[theme]

# Primary accent for interactive elements
primaryColor = '#01F9C6'

# Background color for the main content area
backgroundColor = '#454545'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#B6BBC4'

# Color used for almost all text
textColor = '#FFFFFF'


# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"